name: fast_flutter_driver_tool
description: Toolkit for running rapidly flutter driver tests on desktop.
version: 4.0.2
homepage: https://github.com/tomaszpolanski/fast_flutter_driver

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  fastdriver: main

dependencies:
  args: ^2.4.0
  cli_util: ^0.4.0
  meta: ^1.3.0
  path: ^1.8.0
  process_run: ^0.13.0
  yaml: ^3.1.0
  http: ^1.1.0

dev_dependencies:
  test: ^1.16.0
  mockito: ^5.0.0
  coverage: ^1.0.1
  file: ^6.1.0
  build_runner: ^2.1.2

dependency_overrides:
  built_value: ^8.1.2
