name: fast_flutter_driver_tool
description: Toolkit for running rapidly flutter driver tests on desktop.
version: 4.0.4
homepage: https://github.com/tomaszpolanski/fast_flutter_driver

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  fastdriver: main

dependencies:
  args: ^2.4.2
  cli_util: ^0.4.0
  meta: ^1.11.0
  path: ^1.9.0
  process_run: ^0.13.3
  yaml: ^3.1.2
  http: ^1.1.2
  built_value: ^8.8.0

dev_dependencies:
  test: ^1.24.9
  mockito: ^5.4.3
  coverage: ^1.7.1
  file: ^6.1.4
  build_runner: ^2.4.7

dependency_overrides:
  built_value: ^8.8.0
