name: fast_flutter_driver
description: Toolkit for running rapidly flutter driver tests on desktop.
version: 4.0.0+2
homepage: https://github.com/tomaszpolanski/fast_flutter_driver

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.4.0
  fast_flutter_driver_tool: 
    git:
      url: https://github.com/Gorniv/fast_flutter_driver
      path: tool

  bitsdojo_window: 
    git:
      url: https://github.com/Gorniv/bitsdojo_window
      path: bitsdojo_window
      ref: e0719a45454c5e69a8cd9534a385627b2ec0d448

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: 
  mockito: 

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: WindowUtils
